/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba_conexion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nico-
 */
public class AVALES extends javax.swing.JFrame {

    /**
     * Creates new form AVALES
     */
    public AVALES() {
        initComponents();
          mostrar("");
        txtcod.setEditable(false);
            txtrazsoc.setEditable(false);
            txtdoc.setEditable(false);
            txtnumdoc.setEditable(false); 
            txtap.setEditable(false);
            txtam.setEditable(false);
            txtnom.setEditable(false);
            txtdir.setEditable(false); 
              txttel.setEditable(false);
            txtestado.setEditable(false); 
             valbuscar.setEditable(false);
             cestado.removeAllItems();
            this.iniciarcomboestado();
            cestado.setVisible(false);
             cdocumento.removeAllItems();
            this.iniciarcombodocumento();
            cdocumento.setVisible(false);
            contador++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        labelx3 = new javax.swing.JLabel();
        txtrazsoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdoc = new javax.swing.JTextField();
        cdocumento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtnumdoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdir = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        cestado = new javax.swing.JComboBox<>();
        valbuscar = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();
        MOSTRAR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableavales = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ADICIONAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        INACTIVAR = new javax.swing.JButton();
        REACTIVAR = new javax.swing.JButton();
        ACEPTAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        jLabel1.setText("AVALES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setText("CODIGO:");

        labelx3.setText("RAZON SOCIAL:");

        jLabel3.setText("TIPO DE DOCUMENTO DE IDENTIFICACION:");

        cdocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdocumentoActionPerformed(evt);
            }
        });

        jLabel4.setText("NUMERO DE DOCUMENTO DE IDENTIFICACION:");

        jLabel5.setText("APELLIDO PATERNO:");

        jLabel6.setText("APELLIDO MATERNO:");

        jLabel7.setText("NOMBRE:");

        jLabel8.setText("TELEFONO:");

        jLabel9.setText("DIRRECCCION:");

        jLabel10.setText("ESTADO:");

        cestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cestadoActionPerformed(evt);
            }
        });

        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        MOSTRAR.setText("MOSTRAR");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(labelx3)
                        .addGap(18, 18, 18)
                        .addComponent(txtrazsoc, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtnumdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtap, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BUSCAR))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MOSTRAR))))))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelx3)
                    .addComponent(txtrazsoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtnumdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR)
                    .addComponent(MOSTRAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        tableavales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableavales);

        jPanel4.setBackground(new java.awt.Color(51, 255, 255));

        ADICIONAR.setText("ADICIONAR");
        ADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARActionPerformed(evt);
            }
        });

        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        INACTIVAR.setText("INACTIVAR");
        INACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INACTIVARActionPerformed(evt);
            }
        });

        REACTIVAR.setText("REACTIVAR");
        REACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REACTIVARActionPerformed(evt);
            }
        });

        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(INACTIVAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(REACTIVAR))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ADICIONAR)
                        .addGap(29, 29, 29)
                        .addComponent(MODIFICAR)))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ELIMINAR)
                    .addComponent(ACEPTAR))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CANCELAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SALIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADICIONAR)
                    .addComponent(MODIFICAR)
                    .addComponent(ELIMINAR)
                    .addComponent(SALIR))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INACTIVAR)
                    .addComponent(REACTIVAR)
                    .addComponent(ACEPTAR)
                    .addComponent(CANCELAR))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 250, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cestadoActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM ESTADO WHERE EstNom='"+cestado.getSelectedItem()+"'");
            result.next();
            txestado=result.getString("EstCod");
            txtestado.setText(txestado);
             } catch (SQLException ex) {
                 Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_cestadoActionPerformed

    private void cdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdocumentoActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM DOCUMENTOIDENTIDAD WHERE DocIdeNom='"+cdocumento.getSelectedItem()+"'");
            result.next();
            txdocumento=String.valueOf(result.getInt("DocIdeCod"));
            txtdoc.setText(txdocumento);
             } catch (SQLException ex) {
                 Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_cdocumentoActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        // TODO add your handling code here:
          if(opcion==0){ 
        valbuscar.setEditable(true);
        opcion=2;
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
        // TODO add your handling code here:
         mostrar("");
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
         clean();
        mostrar("");
        opcion=0;
    }//GEN-LAST:event_CANCELARActionPerformed

    private void ADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARActionPerformed
        // TODO add your handling code here:
          if(opcion==0){
            cestado.setVisible(true);
              cdocumento.setVisible(true);
         txtrazsoc.setEditable(true);
          txtnumdoc.setEditable(true); 
            txtap.setEditable(true);
            txtam.setEditable(true);
            txtnom.setEditable(true);
            txtdir.setEditable(true); 
              txttel.setEditable(true);
             opcion=1;
        }
    }//GEN-LAST:event_ADICIONARActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
             if(opcion==0){ 
        int fila=tableavales.getSelectedRow();
         if(fila>=0){
          cestado.setVisible(true);
          cdocumento.setVisible(true);
            txtcod.setText(tableavales.getValueAt(fila,0).toString());
            txtrazsoc.setText(tableavales.getValueAt(fila,1).toString());
           txtnumdoc.setText(tableavales.getValueAt(fila,2).toString());
            txtap.setText(tableavales.getValueAt(fila,3).toString());
            txtam.setText(tableavales.getValueAt(fila,4).toString());
            txtnom.setText(tableavales.getValueAt(fila,5).toString());
            txtdir.setText(tableavales.getValueAt(fila,6).toString());
              txttel.setText(tableavales.getValueAt(fila,7).toString());
              txtdoc.setText(tableavales.getValueAt(fila,8).toString());
            txtestado.setText(tableavales.getValueAt(fila,9).toString());
             
           opcion=3;
          txtrazsoc.setEditable(true);
          txtnumdoc.setEditable(true); 
            txtap.setEditable(true);
            txtam.setEditable(true);
            txtnom.setEditable(true);
            txtdir.setEditable(true); 
              txttel.setEditable(true);
            
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
         }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void INACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INACTIVARActionPerformed
        //       
        if(opcion==0){ 
        int fila=tableavales.getSelectedRow();
         if(fila>=0){
         txtcod.setText(tableavales.getValueAt(fila,0).toString());
            txtrazsoc.setText(tableavales.getValueAt(fila,1).toString());
           txtnumdoc.setText(tableavales.getValueAt(fila,2).toString());
            txtap.setText(tableavales.getValueAt(fila,3).toString());
            txtam.setText(tableavales.getValueAt(fila,4).toString());
            txtnom.setText(tableavales.getValueAt(fila,5).toString());
            txtdir.setText(tableavales.getValueAt(fila,6).toString());
              txttel.setText(tableavales.getValueAt(fila,7).toString());
              txtdoc.setText(tableavales.getValueAt(fila,8).toString());
            txtestado.setText(tableavales.getValueAt(fila,9).toString());
             opcion=4;
          }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
        } 
        
    }//GEN-LAST:event_INACTIVARActionPerformed

    private void REACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REACTIVARActionPerformed
        // TODO add your handling code here:
        if(opcion==0){ 
         int fila=tableavales.getSelectedRow();
         if(fila>=0){
         txtcod.setText(tableavales.getValueAt(fila,0).toString());
            txtrazsoc.setText(tableavales.getValueAt(fila,1).toString());
           txtnumdoc.setText(tableavales.getValueAt(fila,2).toString());
            txtap.setText(tableavales.getValueAt(fila,3).toString());
            txtam.setText(tableavales.getValueAt(fila,4).toString());
            txtnom.setText(tableavales.getValueAt(fila,5).toString());
            txtdir.setText(tableavales.getValueAt(fila,6).toString());
              txttel.setText(tableavales.getValueAt(fila,7).toString());
              txtdoc.setText(tableavales.getValueAt(fila,8).toString());
            txtestado.setText(tableavales.getValueAt(fila,9).toString());
             opcion=5;
          }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
        }
    }//GEN-LAST:event_REACTIVARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){ 
        int fila=tableavales.getSelectedRow();
         if(fila>=0){
         txtcod.setText(tableavales.getValueAt(fila,0).toString());
            txtrazsoc.setText(tableavales.getValueAt(fila,1).toString());
           txtnumdoc.setText(tableavales.getValueAt(fila,2).toString());
            txtap.setText(tableavales.getValueAt(fila,3).toString());
            txtam.setText(tableavales.getValueAt(fila,4).toString());
            txtnom.setText(tableavales.getValueAt(fila,5).toString());
            txtdir.setText(tableavales.getValueAt(fila,6).toString());
              txttel.setText(tableavales.getValueAt(fila,7).toString());
              txtdoc.setText(tableavales.getValueAt(fila,8).toString());
            txtestado.setText(tableavales.getValueAt(fila,9).toString());
             opcion=6;
          }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
         }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        // TODO add your handling code here:
         if(opcion==1){
            try {
                PreparedStatement ps=connection.prepareStatement("INSERT INTO AVALES (AvalRazSoc,AvalNumDoc,AvalApePat,AvalApeMat,AvalNom,AvalDir,AvalTel"
                        + ",DOCUMENTOIDENTIDAD_DocIdeCod,ESTADO_EstCod) VALUES (?,?,?,?,?,?,?,?,?)");
                  ps.setString(1,txtrazsoc.getText());
         ps.setString(2,txtnumdoc.getText());
           ps.setString(3,txtap.getText());
         ps.setString(4,txtam.getText());
         ps.setString(5,txtnom.getText());
         ps.setString(6,txtdir.getText());
           ps.setString(7,txttel.getText());
         ps.setString(8,txdocumento);
          ps.setString(9,txestado);
         ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
            }
             mostrar("");
        }else if(opcion==2){
       mostrar(valbuscar.getText());
        }else if(opcion==3){
             if(txestado.equals(""))
                    txestado=txtestado.getText();
                  if(txdocumento.equals(""))
                    txdocumento=txtdoc.getText();
            try {
                PreparedStatement pst=connection.prepareStatement("UPDATE AVALES SET AvalRazSoc='"
                        +txtrazsoc.getText() +"',AvalNumDoc='"+txtnumdoc.getText()+"',AvalApePat='"+txtap.getText()+"',AvalApeMat='"+txtam.getText()+"',AvalNom='"+txtnom.getText()
                        +"',AvalDir='"+txtdir.getText()+"',AvalTel='"+txttel.getText()+
                        "',DOCUMENTOIDENTIDAD_DocIdeCod='"+txdocumento+ "',ESTADO_EstCod='"+txestado+"' WHERE AvalCod='"+
                        txtcod.getText()+"'");
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
            }
             mostrar("");
             }else if(opcion==4){
             String i ="I";
             
            try {
                PreparedStatement pst=connection.prepareStatement("UPDATE AVALES SET ESTADO_EstCod='"+i+
                        "' WHERE AvalCod='"
                        +txtcod.getText()+"'");
                 pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrar("");
             }else if(opcion==5){
             String i ="A";
             
            try {
                PreparedStatement pst=connection.prepareStatement("UPDATE AVALES SET ESTADO_EstCod='"+i+
                        "' WHERE AvalCod='"
                        +txtcod.getText()+"'");
                 pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrar("");
             }else if(opcion==6){
            try {
                 String i="*";
                PreparedStatement pst=connection.prepareStatement("UPDATE AVALES SET ESTADO_EstCod='"+i+
                        "' WHERE AvalCod='"
                        +txtcod.getText()+"'");
                 pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
            }
                 mostrar("");
             }
          clean();
       opcion=0;
       
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        Conexion_formulario h=new Conexion_formulario();
        h.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
     public void iniciarcombodocumento(){
        
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM DOCUMENTOIDENTIDAD");
             
             while(result.next()){
                 cdocumento.addItem(result.getString("DocIdeNom"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           cdocumento.setVisible(false);
    }
    public void iniciarcomboestado(){
        
        
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM ESTADO");
             
             while(result.next()){
                 cestado.addItem(result.getString("EstNom"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
        }
            cestado.setVisible(false);
    }
     public void mostrar(String valor){
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("CODIGO");
     modelo.addColumn("R SOCIAL");
      modelo.addColumn("NUMDOCIDE");
        modelo.addColumn("AP PATERNO");
     modelo.addColumn("AP MATERNO");
      modelo.addColumn("NOMBRE");
        modelo.addColumn("DIRRECCION");
     modelo.addColumn("TELEFONO");
      modelo.addColumn("DOCID");
       modelo.addColumn("ESTADO");
      tableavales.setModel(modelo);
      String datos[]=new String[10]; 
      String texto="SELECT * FROM AVALES";
    
    if(valor.equals("")==false)
          texto="SELECT * FROM AVALES WHERE AvalCod='"+valor+"'";
     
        try {
            Statement st=connection.createStatement();
              ResultSet result=st.executeQuery(texto);
            while(result.next()){
            datos[0]=result.getString(1);
            datos[1]=result.getString(2);
              datos[2]=result.getString(3);
              datos[3]=result.getString(4);
            datos[4]=result.getString(5);
              datos[5]=result.getString(6);
              datos[6]=result.getString(7);
            datos[7]=result.getString(8);
              datos[8]=result.getString(9);
                datos[9]=result.getString(10);
            modelo.addRow(datos);
            }
            tableavales.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(AVALES.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          
    }
    public void clean(){
     txtcod.setText("");
            txtrazsoc.setText("");
            txtdoc.setText("");
            txtnumdoc.setText("");
            txtap.setText("");
            txtam.setText("");
            txtnom.setText("");
            txtdir.setText("");
              txttel.setText("");
            txtestado.setText("");
             valbuscar.setText("");
    txtcod.setEditable(false);
            txtrazsoc.setEditable(false);
            txtdoc.setEditable(false);
            txtnumdoc.setEditable(false); 
            txtap.setEditable(false);
            txtam.setEditable(false);
            txtnom.setEditable(false);
            txtdir.setEditable(false); 
              txttel.setEditable(false);
            txtestado.setEditable(false); 
             valbuscar.setEditable(false);
    cestado.setVisible(false);
    txestado="";
    cdocumento.setVisible(false);
    txdocumento="";
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AVALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AVALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AVALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AVALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AVALES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton ADICIONAR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton INACTIVAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JButton REACTIVAR;
    private javax.swing.JButton SALIR;
    private javax.swing.JComboBox<String> cdocumento;
    private javax.swing.JComboBox<String> cestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelx3;
    private javax.swing.JTable tableavales;
    private javax.swing.JTextField txtam;
    private javax.swing.JTextField txtap;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnumdoc;
    private javax.swing.JTextField txtrazsoc;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField valbuscar;
    // End of variables declaration//GEN-END:variables
int opcion=0;
int contador=0;
String txestado="";
String txdocumento="";
    Conectar co=new Conectar();
Connection connection=co.conexion();


}
