/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba_conexion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nico-
 */
public class LUGARGIRO extends javax.swing.JFrame {

    /**
     * Creates new form LUGARGIRO
     */
    
    public LUGARGIRO() {
        initComponents();
        mostrar("");
        txtcod.setEditable(false);
            txtnom.setEditable(false);
            valbuscar.setEditable(false);
             txtestado.setEditable(false);
            cestado.removeAllItems();
            this.iniciarcombo();
            contador++;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtest = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cestado = new javax.swing.JComboBox<>();
        txtestado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnadicionar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btninactivar = new javax.swing.JButton();
        btnreactivar = new javax.swing.JButton();
        btnaceptar = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablelugargiro = new javax.swing.JTable();
        valbuscar = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();
        MOSTRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("0ZZ001");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("CODIGO(6):");

        jLabel3.setText("LUGAR:");

        jLabel4.setText("ESTADO:");

        cestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cestadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtestLayout = new javax.swing.GroupLayout(txtest);
        txtest.setLayout(txtestLayout);
        txtestLayout.setHorizontalGroup(
            txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(txtestLayout.createSequentialGroup()
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtestLayout.setVerticalGroup(
            txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtestLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(txtestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setForeground(new java.awt.Color(0, 255, 255));

        btnadicionar.setText("ADICIONAR");
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btninactivar.setText("INACTIVAR");
        btninactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninactivarActionPerformed(evt);
            }
        });

        btnreactivar.setText("REACTIVAR");
        btnreactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreactivarActionPerformed(evt);
            }
        });

        btnaceptar.setText("ACEPTAR");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnadicionar)
                        .addGap(26, 26, 26)
                        .addComponent(btnmodificar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btninactivar)
                        .addGap(39, 39, 39)
                        .addComponent(btnreactivar)))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar)
                    .addComponent(btnaceptar))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnsalir))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(CANCELAR)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadicionar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar)
                    .addComponent(btnsalir))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninactivar)
                    .addComponent(btnreactivar)
                    .addComponent(btnaceptar)
                    .addComponent(CANCELAR))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        tablelugargiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablelugargiro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        MOSTRAR.setText("MOSTRAR");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BUSCAR)
                .addGap(18, 18, 18)
                .addComponent(MOSTRAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR)
                    .addComponent(MOSTRAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed
             if(opcion==0){   
              cestado.setVisible(true);
        txtcod.setEditable(true);
            txtnom.setEditable(true);
              opcion=1;     
        
             }
    }//GEN-LAST:event_btnadicionarActionPerformed

    private void btninactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninactivarActionPerformed
        // TODO add your handling code here:
        if(opcion==0){ 
        int fila=tablelugargiro.getSelectedRow();
         if(fila>=0){
             txtcod.setText(tablelugargiro.getValueAt(fila,0).toString());
             txtnom.setText(tablelugargiro.getValueAt(fila,1).toString());
           txtestado.setText(tablelugargiro.getValueAt(fila,2).toString());
            opcion=4;
         cestado.setVisible(false);
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
         }
    }//GEN-LAST:event_btninactivarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
          if(opcion==0){  
        int fila=tablelugargiro.getSelectedRow();
         if(fila>=0){
             
             txtcod.setText(tablelugargiro.getValueAt(fila,0).toString());
             txtnom.setText(tablelugargiro.getValueAt(fila,1).toString());
             txtestado.setText(tablelugargiro.getValueAt(fila,2).toString());
           opcion=3;
         txtcod.setEditable(true);
            txtnom.setEditable(true);
            cestado.setVisible(true);
            
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         } 
         }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
       if(opcion==1){
        try {
            // TODO add your handling code here:
            PreparedStatement ps=connection.prepareStatement("INSERT INTO LUGARGIRO (LugGirCod,LugGirNom,ESTADO_EstCod) VALUES (?,?,?)");
        ps.setString(1,txtcod.getText());
        ps.setString(2,txtnom.getText());
         ps.setString(3,txestado);
        ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(LUGARGIRO.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error");
        }
        
       mostrar("");
        
       }else if(opcion==2){
       mostrar(valbuscar.getText().toString());
        }else if(opcion==3){
           if(txestado.equals(""))
               txestado=txtestado.getText();
           try {
               PreparedStatement pst=connection.prepareStatement("UPDATE LUGARGIRO SET LugGirNom='"
                      +txtnom.getText() + "',ESTADO_EstCod='"+txestado+"' WHERE LugGirCod='"+
                       txtcod.getText()+"'");
               pst.executeUpdate();
               
           } catch (SQLException ex) {
               Logger.getLogger(LUGARGIRO.class.getName()).log(Level.SEVERE, null, ex);
           }
        mostrar("");
        }else if(opcion==4){
           try {
               String i ="I";
               PreparedStatement pst=connection.prepareStatement("UPDATE LUGARGIRO SET ESTADO_EstCod='"+i+
                 "' WHERE LugGirCod='"
                +txtcod.getText()+"'");
               pst.executeUpdate();
           } catch (SQLException ex) {
               Logger.getLogger(LUGARGIRO.class.getName()).log(Level.SEVERE, null, ex);
           }
           mostrar("");
        }else if(opcion==5){
           try {
               String i ="A";
               PreparedStatement pst=connection.prepareStatement("UPDATE LUGARGIRO SET ESTADO_EstCod='"+i+
                 "' WHERE LugGirCod='"
                +txtcod.getText()+"'");
               pst.executeUpdate();
           } catch (SQLException ex) {
               Logger.getLogger(LUGARGIRO.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           mostrar("");
        }else if(opcion==6){
           try {
               
              String i ="*";
               PreparedStatement pst=connection.prepareStatement("UPDATE LUGARGIRO SET ESTADO_EstCod='"+i+
                 "' WHERE LugGirCod='"
                +txtcod.getText()+"'");
               pst.executeUpdate();
           } catch (SQLException ex) {
               Logger.getLogger(LUGARGIRO.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           mostrar("");
        }
       clean();
       opcion=0;
        

    }//GEN-LAST:event_btnaceptarActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        clean();
        mostrar("");
        opcion=0;
        
    }//GEN-LAST:event_CANCELARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){  
        valbuscar.setEditable(true);
        opcion=2;
         }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
        // TODO add your handling code here:
        mostrar("");
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void btnreactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreactivarActionPerformed
        // TODO add your handling code here:
         if(opcion==0){  
        int fila=tablelugargiro.getSelectedRow();
         if(fila>=0){
             
             txtcod.setText(tablelugargiro.getValueAt(fila,0).toString());
             txtnom.setText(tablelugargiro.getValueAt(fila,1).toString());
            txtestado.setText(tablelugargiro.getValueAt(fila,2).toString());
           opcion=5;
         cestado.setVisible(false);
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
         }
    }//GEN-LAST:event_btnreactivarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
         if(opcion==0){  
        int fila=tablelugargiro.getSelectedRow();
         if(fila>=0){
             
             txtcod.setText(tablelugargiro.getValueAt(fila,0).toString());
             txtnom.setText(tablelugargiro.getValueAt(fila,1).toString());
            txtestado.setText(tablelugargiro.getValueAt(fila,2).toString());
           opcion=6;
            cestado.setVisible(false);
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         } 
         }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        Conexion_formulario h=new Conexion_formulario();
        h.setVisible(true); 
        this.dispose();
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void cestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cestadoActionPerformed
      if(this.contador>0){ 
        try {
            // TODO add your handling code here:
            Statement st=connection.createStatement();
            ResultSet result=st.executeQuery("SELECT *FROM ESTADO WHERE EstNom='"+cestado.getSelectedItem()+"'");
            result.next();
            txestado=result.getString("EstCod");
            txtestado.setText(txestado);
        } catch (SQLException ex) {
            Logger.getLogger(LUGARGIRO.class.getName()).log(Level.SEVERE, null, ex);
        }
             
      }
    }//GEN-LAST:event_cestadoActionPerformed
   
    
    
    /**
     * @param args the command line arguments
     */
    
    public void mostrar(String valor){
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("CODIGO");
     modelo.addColumn("LUGAR DE GIRO");
      modelo.addColumn("ESTADO");
      tablelugargiro.setModel(modelo);
      String datos[]=new String[3]; 
      String texto="SELECT * FROM LUGARGIRO";
      if(valor.equals("")==false)
          texto="SELECT * FROM LUGARGIRO WHERE LugGirCod='"+valor+"'";
      try {
            Statement st=connection.createStatement();
            ResultSet result=st.executeQuery(texto);
            while(result.next()){
            datos[0]=result.getString(1);
            datos[1]=result.getString(2);
              datos[2]=result.getString(3);
            modelo.addRow(datos);
             }
            tablelugargiro.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(LUGARGIRO.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    public void clean(){
    txtcod.setText("");
    txtnom.setText("");
    txtestado.setText("");
    valbuscar.setText("");
    txtcod.setEditable(false);
            txtnom.setEditable(false);
            txtestado.setEditable(false);
           valbuscar.setEditable(false);  
           cestado.setVisible(false);
           txestado="";
    
    }
    public void iniciarcombo(){
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM ESTADO");
             
             while(result.next()){
                 cestado.addItem(result.getString("EstNom"));
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(LUGARGIRO.class.getName()).log(Level.SEVERE, null, ex);
        }
           cestado.setVisible(false);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LUGARGIRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LUGARGIRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LUGARGIRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LUGARGIRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LUGARGIRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnadicionar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btninactivar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnreactivar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablelugargiro;
    private javax.swing.JTextField txtcod;
    private javax.swing.JPanel txtest;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField valbuscar;
    // End of variables declaration//GEN-END:variables
int opcion=0;
int contador=0;
String txestado="";
    Conectar co=new Conectar();
Connection connection=co.conexion();
}
