/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba_conexion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nico-
 */
public class REGISTROLETRASCAMBIO extends javax.swing.JFrame {

    /**
     * Creates new form REGISTROLETRASCAMBIO
     */
    public REGISTROLETRASCAMBIO() {
        initComponents();
        mostrar("");
        txtcod.setEditable(false);
            txtref1.setEditable(false);
            txtref2.setEditable(false);
            txtgiroaño.setEditable(false);
            txtgiromes.setEditable(false);
            txtgirodia.setEditable(false);
            txtvenaño.setEditable(false);
            txtvenmes.setEditable(false);
              txtvendia.setEditable(false);
               txtmonto.setEditable(false);
            txtlug.setEditable(false);
              txtmon.setEditable(false);
            txtacep.setEditable(false);
            txtaval.setEditable(false);
              txtban.setEditable(false);
            txtrep.setEditable(false);
            txtestado.setEditable(false);
             valbuscar.setEditable(false);
             cestado.removeAllItems();
              clugar.removeAllItems();
              cmoneda.removeAllItems();
              caceptante.removeAllItems();
            caval.removeAllItems();
              crepresentante.removeAllItems();
              cbanco.removeAllItems();
   this.iniciarcomboaceptante();
   this.iniciarcomboaval();
   this.iniciarcombobanco();
   this.iniciarcomboestado();
   this.iniciarcombolugargiro();
   this.iniciarcombotipomoneda();
   this.iniciarrepresentantegirador();
    cestado.setVisible(false);
    clugar.setVisible(false);
    cmoneda.setVisible(false);
    caceptante.setVisible(false);
    caval.setVisible(false);
    crepresentante.setVisible(false);
    cbanco.setVisible(false);
   
    contador++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtref1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtref2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtlug = new javax.swing.JTextField();
        clugar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtmon = new javax.swing.JTextField();
        cmoneda = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtacep = new javax.swing.JTextField();
        caceptante = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtaval = new javax.swing.JTextField();
        caval = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtban = new javax.swing.JTextField();
        cbanco = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtrep = new javax.swing.JTextField();
        crepresentante = new javax.swing.JComboBox<>();
        txtgirodia = new javax.swing.JTextField();
        txtgiromes = new javax.swing.JTextField();
        txtgiroaño = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        txtvendia = new javax.swing.JTextField();
        txtvenmes = new javax.swing.JTextField();
        txtvenaño = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        cestado = new javax.swing.JComboBox<>();
        valbuscar = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();
        MOSTRAR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableregistro = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ADICIONAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        INACTIVAR = new javax.swing.JButton();
        ACEPTAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        REACTIVAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("REGISTRO DE LETRAS DE CAMBIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        jLabel3.setText("CODIGO:");

        jLabel2.setText("REFERENCIA 1:");

        jLabel4.setText("REFERENCIA 2 :");

        jLabel5.setText("LUGAR GIRO:");

        clugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clugarActionPerformed(evt);
            }
        });

        jLabel6.setText("TIPO DE MONEDA:");

        txtmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmonActionPerformed(evt);
            }
        });

        cmoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmonedaActionPerformed(evt);
            }
        });

        jLabel7.setText("ACEPTANTE:");

        caceptante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        caceptante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caceptanteActionPerformed(evt);
            }
        });

        jLabel8.setText("AVAL:");

        caval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        caval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cavalActionPerformed(evt);
            }
        });

        jLabel9.setText("BANCOS:");

        cbanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbancoActionPerformed(evt);
            }
        });

        jLabel10.setText("REPRESENTANTE LEGAL:");

        crepresentante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        crepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crepresentanteActionPerformed(evt);
            }
        });

        jLabel11.setText("              FECHA DE GIRO");

        jLabel12.setText("DIA");

        jLabel13.setText("MES");

        jLabel14.setText("AÑO");

        jLabel15.setText("FECHA DE VENCIMIENTO");

        txtvenmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvenmesActionPerformed(evt);
            }
        });

        jLabel16.setText("DIA");

        jLabel17.setText("MES");

        jLabel18.setText("AÑO");

        jLabel19.setText("MONTO:");

        jLabel20.setText("ESTADO:");

        cestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cestadoActionPerformed(evt);
            }
        });

        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        MOSTRAR.setText("MOSTRAR");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel12))
                                    .addComponent(txtgirodia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtgiromes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtacep, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtgiroaño, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtvendia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel18))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtvenmes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtvenaño)))
                                        .addGap(97, 97, 97))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(caceptante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel8)
                                                .addGap(31, 31, 31)
                                                .addComponent(txtaval, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(caval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtrep, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(crepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(567, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(22, 22, 22)
                                        .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtlug, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(clugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtmon, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(cmoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtban, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(cbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(txtref1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addComponent(txtref2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(BUSCAR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(MOSTRAR)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtref2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtlug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtacep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caceptante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtaval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtgirodia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgiromes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgiroaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvendia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvenmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvenaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR)
                    .addComponent(MOSTRAR))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tableregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableregistro);

        ADICIONAR.setText("ADICIONAR");
        ADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARActionPerformed(evt);
            }
        });

        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        INACTIVAR.setText("INACTIVAR");
        INACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INACTIVARActionPerformed(evt);
            }
        });

        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        REACTIVAR.setText("REACTIVAR");
        REACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REACTIVARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADICIONAR)
                    .addComponent(INACTIVAR))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MODIFICAR)
                    .addComponent(REACTIVAR))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ELIMINAR)
                        .addGap(18, 18, 18)
                        .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ACEPTAR)
                        .addGap(21, 21, 21)
                        .addComponent(CANCELAR)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADICIONAR)
                    .addComponent(MODIFICAR)
                    .addComponent(ELIMINAR)
                    .addComponent(SALIR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(INACTIVAR)
                            .addComponent(ACEPTAR)
                            .addComponent(CANCELAR)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(REACTIVAR)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(852, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmonActionPerformed

    private void txtvenmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvenmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvenmesActionPerformed

    private void cestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cestadoActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM ESTADO WHERE EstNom='"+cestado.getSelectedItem()+"'");
            result.next();
            txestado=result.getString("EstCod");
            txtestado.setText(txestado);
             } catch (SQLException ex) {
                 Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        
    }//GEN-LAST:event_cestadoActionPerformed

    private void clugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clugarActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM LUGARGIRO WHERE LugGirNom='"+clugar.getSelectedItem()+"'");
            result.next();
            txlugargiro=result.getString("LugGirCod");
            txtlug.setText(txlugargiro);
             } catch (SQLException ex) {
                 Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_clugarActionPerformed

    private void cmonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmonedaActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM TIPOMONEDA WHERE TipMonNom='"+cmoneda.getSelectedItem()+"'");
            result.next();
            txmoneda=String.valueOf(result.getInt("TipMonCod"));
            txtmon.setText(txmoneda);
             } catch (SQLException ex) {
                 Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_cmonedaActionPerformed

    private void cbancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbancoActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM BANCOS WHERE BanNom='"+cbanco.getSelectedItem()+"'");
            result.next();
            txbanco=String.valueOf(result.getInt("BanCod"));
            txtban.setText(txbanco);
             } catch (SQLException ex) {
                 Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_cbancoActionPerformed

    private void caceptanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caceptanteActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM ACEPTANTE WHERE AcepCod='"+caceptante.getSelectedItem()+"'");
            result.next();
            txaceptante=String.valueOf(result.getInt("AcepCod"));
            txtacep.setText(txaceptante);
             } catch (SQLException ex) {
                 Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_caceptanteActionPerformed

    private void cavalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cavalActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM AVALES WHERE AvalCod='"+caval.getSelectedItem()+"'");
            result.next();
            txaval=String.valueOf(result.getInt("AvalCod"));
            txtaval.setText(txaval);
             } catch (SQLException ex) {
                 Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_cavalActionPerformed

    private void crepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crepresentanteActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                  ResultSet result=st.executeQuery("SELECT *FROM REPRESENTANTEGIRADOR WHERE RepGir='"+crepresentante.getSelectedItem()+"'");
            result.next();
            txrepresentante=String.valueOf(result.getInt("RepGir"));
            txtrep.setText(txrepresentante);
             } catch (SQLException ex) {
                 Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_crepresentanteActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
          clean();
        mostrar("");
        opcion=0;
    }//GEN-LAST:event_CANCELARActionPerformed

    private void ADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){
           txtref1.setEditable(true);
            txtref2.setEditable(true);
            txtgiroaño.setEditable(true);
            txtgiromes.setEditable(true);
            txtgirodia.setEditable(true);
            txtvenaño.setEditable(true);
            txtvenmes.setEditable(true);
              txtvendia.setEditable(true);
               txtmonto.setEditable(true);
            txtlug.setEditable(false);
              txtmon.setEditable(false);
            txtacep.setEditable(false);
            txtaval.setEditable(false);
              txtban.setEditable(false);
            txtrep.setEditable(false);
            txtestado.setEditable(false);
             valbuscar.setEditable(false);
             cestado.setVisible(true);
    clugar.setVisible(true);
    cmoneda.setVisible(true);
    caceptante.setVisible(true);
    caval.setVisible(true);
    crepresentante.setVisible(true);
    cbanco.setVisible(true);
             opcion=1;
        }
    }//GEN-LAST:event_ADICIONARActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
        // TODO add your handling code here:
        this.mostrar("");
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        // TODO add your handling code here:
          if(opcion==0){ 
        valbuscar.setEditable(true);
        opcion=2;
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        // TODO add your handling code here:
                 if(opcion==1){
            try {
                PreparedStatement ps=connection.prepareStatement("INSERT INTO REGISTROLETRASCAMBIO (RegLetCamRef1,RegLetCamRef2,RegLetCamFecGirAño,RegLetCamFecGirMes,RegLetCamFecGirDia,RegLetCamFecVenAño,RegLetCamFecVenMes,RegLetCamFecVenDia,RegLetCamMont,"
                        + "LUGARGIRO_LugGirCod,TIPOMONEDA_TipMonCod,ACEPTANTE_AcepCod,AVALES_AvalCod,BANCOS_BanCod,REPRESENTANTEGIRADOR_RepGir1,ESTADO_EstCod) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                  ps.setString(1,txtref1.getText());
         ps.setString(2,txtref2.getText());
           ps.setString(3,txtgiroaño.getText());
         ps.setString(4,txtgiromes.getText());
         ps.setString(5,txtgirodia.getText());
         ps.setString(6,txtvenaño.getText());
           ps.setString(7,txtvenmes.getText());
         ps.setString(8,txtvendia.getText());
         ps.setString(9,txtmonto.getText());
          ps.setString(10,txlugargiro);
           ps.setString(11,txmoneda);
            ps.setString(12,txaceptante);
           ps.setString(13,txaval);
           ps.setString(14,txbanco);
            ps.setString(15,txrepresentante);
           ps.setString(16,txestado);
         ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
            }
             mostrar("");
        }else if(opcion==2){
       mostrar(valbuscar.getText().toString());
        }else if(opcion==3){
             if(txlugargiro.equals(""))
                    txlugargiro=txtlug.getText();
                  if(txmoneda.equals(""))
                    txmoneda=txtmon.getText();
                   if(txaceptante.equals(""))
                    txaceptante=txtacep.getText();
                  if(txaval.equals(""))
                    txaval=txtaval.getText();
                   if(txbanco.equals(""))
                    txbanco=txtban.getText();
                   if(txrepresentante.equals(""))
                    txrepresentante=txtrep.getText();
                  if(txestado.equals(""))
                    txestado=txtestado.getText();
            try {
                PreparedStatement pst=connection.prepareStatement("UPDATE REGISTROLETRASCAMBIO SET RegLetCamRef1='"
                        +txtref1.getText() +"', RegLetCamRef2='"+txtref2.getText()+"', RegLetCamFecGirAño='"+txtgiroaño.getText()+"', RegLetCamFecGirMes='"+txtgiromes.getText()+"', RegLetCamFecGirDia='"+txtgirodia.getText()+"', RegLetCamFecVenAño='"+txtvenaño.getText()+"', RegLetCamFecVenMes='"+txtvenmes.getText()+"', RegLetCamFecVenDia='"+txtvendia.getText()+"', RegLetCamMont='"+txtmonto.getText()+"',LUGARGIRO_LugGirCod='"+txlugargiro+"',TIPOMONEDA_TipMonCod='"+txmoneda+"',ACEPTANTE_AcepCod='"+txaceptante+"',AVALES_AvalCod='"+txaval+"',BANCOS_BanCod='"+txbanco+"',REPRESENTANTEGIRADOR_RepGir1='"+txrepresentante+"',ESTADO_EstCod='"+txestado+
                        "' WHERE RegLetCamCod='"+
                        txtcod.getText()+"'");
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
            }
             mostrar("");
        }else if(opcion==4){
             String i ="I";
             
            try {
                PreparedStatement pst=connection.prepareStatement("UPDATE REGISTROLETRASCAMBIO SET ESTADO_EstCod='"+i+
                        "' WHERE RegLetCamCod='"
                        +txtcod.getText()+"'");
                 pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrar("");
             }else if(opcion==5){
             String i ="A";
             
            try {
                PreparedStatement pst=connection.prepareStatement("UPDATE REGISTROLETRASCAMBIO SET ESTADO_EstCod='"+i+
                        "' WHERE RegLetCamCod='"
                        +txtcod.getText()+"'");
                 pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrar("");
             }else if(opcion==6){
            try {
                 String i ="*";
                PreparedStatement pst=connection.prepareStatement("UPDATE REGISTROLETRASCAMBIO SET ESTADO_EstCod='"+i+
                        "' WHERE RegLetCamCod='"
                        +txtcod.getText()+"'");
                 pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
            }
             
                 mostrar("");
          }
                  clean();
       opcion=0;
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:System.exit(1);
        Conexion_formulario h=new Conexion_formulario();
        h.setVisible(true);
         this.dispose();
        
        
    }//GEN-LAST:event_SALIRActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
        if(opcion==0){ 
        int fila=tableregistro.getSelectedRow();
         if(fila>=0){
           cestado.setVisible(true);
    clugar.setVisible(true);
    cmoneda.setVisible(true);
    caceptante.setVisible(true);
    caval.setVisible(true);
    crepresentante.setVisible(true);
    cbanco.setVisible(true);
            txtcod.setText(tableregistro.getValueAt(fila,0).toString());
            txtref1.setText(tableregistro.getValueAt(fila,1).toString());
           txtref2.setText(tableregistro.getValueAt(fila,2).toString());
            txtgiroaño.setText(tableregistro.getValueAt(fila,3).toString());
            txtgiromes.setText(tableregistro.getValueAt(fila,4).toString());
            txtgirodia.setText(tableregistro.getValueAt(fila,5).toString());
            txtvenaño.setText(tableregistro.getValueAt(fila,6).toString());
            txtvenmes.setText(tableregistro.getValueAt(fila,7).toString());
            txtvendia.setText(tableregistro.getValueAt(fila,8).toString());
             txtmonto.setText(tableregistro.getValueAt(fila,9).toString());
            txtlug.setText(tableregistro.getValueAt(fila,10).toString());
            txtmon.setText(tableregistro.getValueAt(fila,11).toString());
             txtacep.setText(tableregistro.getValueAt(fila,12).toString());
            txtaval.setText(tableregistro.getValueAt(fila,13).toString());
             txtban.setText(tableregistro.getValueAt(fila,14).toString());
            txtrep.setText(tableregistro.getValueAt(fila,15).toString());
            txtestado.setText(tableregistro.getValueAt(fila,16).toString());
           opcion=3;
          txtref1.setEditable(true);
            txtref2.setEditable(true);
            txtgiroaño.setEditable(true);
            txtgiromes.setEditable(true);
            txtgirodia.setEditable(true);
            txtvenaño.setEditable(true);
            txtvenmes.setEditable(true);
              txtvendia.setEditable(true);
               txtmonto.setEditable(true);
            txtlug.setEditable(false);
              txtmon.setEditable(false);
            txtacep.setEditable(false);
            txtaval.setEditable(false);
              txtban.setEditable(false);
            txtrep.setEditable(false);
            txtestado.setEditable(false);
             valbuscar.setEditable(false);
            
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
         }
    
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void INACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INACTIVARActionPerformed
        // TODO add your handling code here:
        if(opcion==0){ 
        int fila=tableregistro.getSelectedRow();
         if(fila>=0){
           cestado.setVisible(true);
    clugar.setVisible(true);
    cmoneda.setVisible(true);
    caceptante.setVisible(true);
    caval.setVisible(true);
    crepresentante.setVisible(true);
    cbanco.setVisible(true);
            txtcod.setText(tableregistro.getValueAt(fila,0).toString());
            txtref1.setText(tableregistro.getValueAt(fila,1).toString());
           txtref2.setText(tableregistro.getValueAt(fila,2).toString());
            txtgiroaño.setText(tableregistro.getValueAt(fila,3).toString());
            txtgiromes.setText(tableregistro.getValueAt(fila,4).toString());
            txtgirodia.setText(tableregistro.getValueAt(fila,5).toString());
            txtvenaño.setText(tableregistro.getValueAt(fila,6).toString());
            txtvenmes.setText(tableregistro.getValueAt(fila,7).toString());
            txtvendia.setText(tableregistro.getValueAt(fila,8).toString());
             txtmonto.setText(tableregistro.getValueAt(fila,9).toString());
            txtlug.setText(tableregistro.getValueAt(fila,10).toString());
            txtmon.setText(tableregistro.getValueAt(fila,11).toString());
             txtacep.setText(tableregistro.getValueAt(fila,12).toString());
            txtaval.setText(tableregistro.getValueAt(fila,13).toString());
             txtban.setText(tableregistro.getValueAt(fila,14).toString());
            txtrep.setText(tableregistro.getValueAt(fila,15).toString());
            txtestado.setText(tableregistro.getValueAt(fila,16).toString());
           opcion=4;
         
            
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
        }
    }//GEN-LAST:event_INACTIVARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
             if(opcion==0){ 
        int fila=tableregistro.getSelectedRow();
         if(fila>=0){
           cestado.setVisible(true);
    clugar.setVisible(true);
    cmoneda.setVisible(true);
    caceptante.setVisible(true);
    caval.setVisible(true);
    crepresentante.setVisible(true);
    cbanco.setVisible(true);
            txtcod.setText(tableregistro.getValueAt(fila,0).toString());
            txtref1.setText(tableregistro.getValueAt(fila,1).toString());
           txtref2.setText(tableregistro.getValueAt(fila,2).toString());
            txtgiroaño.setText(tableregistro.getValueAt(fila,3).toString());
            txtgiromes.setText(tableregistro.getValueAt(fila,4).toString());
            txtgirodia.setText(tableregistro.getValueAt(fila,5).toString());
            txtvenaño.setText(tableregistro.getValueAt(fila,6).toString());
            txtvenmes.setText(tableregistro.getValueAt(fila,7).toString());
            txtvendia.setText(tableregistro.getValueAt(fila,8).toString());
             txtmonto.setText(tableregistro.getValueAt(fila,9).toString());
            txtlug.setText(tableregistro.getValueAt(fila,10).toString());
            txtmon.setText(tableregistro.getValueAt(fila,11).toString());
             txtacep.setText(tableregistro.getValueAt(fila,12).toString());
            txtaval.setText(tableregistro.getValueAt(fila,13).toString());
             txtban.setText(tableregistro.getValueAt(fila,14).toString());
            txtrep.setText(tableregistro.getValueAt(fila,15).toString());
            txtestado.setText(tableregistro.getValueAt(fila,16).toString());
           opcion=6;
          }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
   
             }
    }                                         
/*
    private void REACTIVARActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here if(opcion==0){ 
        int fila=tableregistro.getSelectedRow();
         if(fila>=0){
           cestado.setVisible(true);
    clugar.setVisible(true);
    cmoneda.setVisible(true);
    caceptante.setVisible(true);
    caval.setVisible(true);
    crepresentante.setVisible(true);
    cbanco.setVisible(true);
            txtcod.setText(tableregistro.getValueAt(fila,0).toString());
            txtref1.setText(tableregistro.getValueAt(fila,1).toString());
           txtref2.setText(tableregistro.getValueAt(fila,2).toString());
            txtgiroaño.setText(tableregistro.getValueAt(fila,3).toString());
            txtgiromes.setText(tableregistro.getValueAt(fila,4).toString());
            txtgirodia.setText(tableregistro.getValueAt(fila,5).toString());
            txtvenaño.setText(tableregistro.getValueAt(fila,6).toString());
            txtvenmes.setText(tableregistro.getValueAt(fila,7).toString());
            txtvendia.setText(tableregistro.getValueAt(fila,8).toString());
             txtmonto.setText(tableregistro.getValueAt(fila,9).toString());
            txtlug.setText(tableregistro.getValueAt(fila,10).toString());
            txtmon.setText(tableregistro.getValueAt(fila,11).toString());
             txtacep.setText(tableregistro.getValueAt(fila,12).toString());
            txtaval.setText(tableregistro.getValueAt(fila,13).toString());
             txtban.setText(tableregistro.getValueAt(fila,14).toString());
            txtrep.setText(tableregistro.getValueAt(fila,15).toString());
            txtestado.setText(tableregistro.getValueAt(fila,16).toString());
           opcion=5;
         
            
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
        
    }//GEN-LAST:event_ELIMINARActionPerformed
*/ 
    private void REACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REACTIVARActionPerformed
        // TODO add your handling code here:
        if(opcion==0){
        int fila=tableregistro.getSelectedRow();
         if(fila>=0){
           cestado.setVisible(true);
    clugar.setVisible(true);
    cmoneda.setVisible(true);
    caceptante.setVisible(true);
    caval.setVisible(true);
    crepresentante.setVisible(true);
    cbanco.setVisible(true);
            txtcod.setText(tableregistro.getValueAt(fila,0).toString());
            txtref1.setText(tableregistro.getValueAt(fila,1).toString());
           txtref2.setText(tableregistro.getValueAt(fila,2).toString());
            txtgiroaño.setText(tableregistro.getValueAt(fila,3).toString());
            txtgiromes.setText(tableregistro.getValueAt(fila,4).toString());
            txtgirodia.setText(tableregistro.getValueAt(fila,5).toString());
            txtvenaño.setText(tableregistro.getValueAt(fila,6).toString());
            txtvenmes.setText(tableregistro.getValueAt(fila,7).toString());
            txtvendia.setText(tableregistro.getValueAt(fila,8).toString());
             txtmonto.setText(tableregistro.getValueAt(fila,9).toString());
            txtlug.setText(tableregistro.getValueAt(fila,10).toString());
            txtmon.setText(tableregistro.getValueAt(fila,11).toString());
             txtacep.setText(tableregistro.getValueAt(fila,12).toString());
            txtaval.setText(tableregistro.getValueAt(fila,13).toString());
             txtban.setText(tableregistro.getValueAt(fila,14).toString());
            txtrep.setText(tableregistro.getValueAt(fila,15).toString());
            txtestado.setText(tableregistro.getValueAt(fila,16).toString());
           opcion=5;
         
            
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
        }
    }//GEN-LAST:event_REACTIVARActionPerformed

  
     
    
    public void mostrar(String valor){
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("CODIGO");
     modelo.addColumn("REFERENCIA 1");
      modelo.addColumn("REFERENCIA 2");
        modelo.addColumn("FECGIRAÑO");
     modelo.addColumn("FECGIRMES");
      modelo.addColumn("FECGIRDIA");
       modelo.addColumn("FECVENRAÑO");
     modelo.addColumn("FECVENMES");
      modelo.addColumn("FECVENDIA");
        modelo.addColumn("MONTO");
     modelo.addColumn("LUGARGIRO");
      modelo.addColumn("MONEDA");
       modelo.addColumn("ACEPTANTE");
        modelo.addColumn("AVAL");
     modelo.addColumn("BANCO");
      modelo.addColumn("REPRESENTANTE");
       modelo.addColumn("ESTADO");
      tableregistro.setModel(modelo);
      String datos[]=new String[17]; 
      String texto="SELECT * FROM REGISTROLETRASCAMBIO";
    
    if(valor.equals("")==false)
          texto="SELECT * FROM REGISTROLETRASCAMBIO WHERE RegLetCamCod='"+valor+"'";
     
        try {
            Statement st=connection.createStatement();
              ResultSet result=st.executeQuery(texto);
            while(result.next()){
            datos[0]=result.getString(1);
            datos[1]=result.getString(2);
              datos[2]=result.getString(3);
              datos[3]=result.getString(4);
            datos[4]=result.getString(5);
              datos[5]=result.getString(6);
              datos[6]=result.getString(7);
            datos[7]=result.getString(8);
              datos[8]=result.getString(9);
                datos[9]=result.getString(10);
                  datos[10]=result.getString(11);
            datos[11]=result.getString(12);
              datos[12]=result.getString(13);
              datos[13]=result.getString(14);
            datos[14]=result.getString(15);
              datos[15]=result.getString(16);
                datos[16]=result.getString(17);
            modelo.addRow(datos);
            }
            tableregistro.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          
    }
    public void clean(){
     txtcod.setText("");
            txtref1.setText("");
            txtref2.setText("");
            txtgiroaño.setText("");
            txtgiromes.setText("");
            txtgirodia.setText("");
            txtvenaño.setText("");
            txtvenmes.setText("");
              txtvendia.setText("");
               txtmonto.setText("");
            txtlug.setText("");
              txtmon.setText("");
            txtacep.setText("");
            txtaval.setText("");
              txtban.setText("");
            txtrep.setText("");
            txtestado.setText("");
             valbuscar.setText("");
     txtcod.setEditable(false);
            txtref1.setEditable(false);
            txtref2.setEditable(false);
            txtgiroaño.setEditable(false);
            txtgiromes.setEditable(false);
            txtgirodia.setEditable(false);
            txtvenaño.setEditable(false);
            txtvenmes.setEditable(false);
              txtvendia.setEditable(false);
               txtmonto.setEditable(false);
            txtlug.setEditable(false);
              txtmon.setEditable(false);
            txtacep.setEditable(false);
            txtaval.setEditable(false);
              txtban.setEditable(false);
            txtrep.setEditable(false);
            txtestado.setEditable(false);
             valbuscar.setEditable(false);
    cestado.setVisible(false);
    clugar.setVisible(false);
    cmoneda.setVisible(false);
    caceptante.setVisible(false);
    caval.setVisible(false);
    crepresentante.setVisible(false);
    cbanco.setVisible(false);
    String txlugargiro="";
String txmoneda="";
String txaceptante="";
String txaval="";
String txbanco="";
String txrepresentante="";
String txestado="";
   
    }
 public void iniciarcomboestado(){
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM ESTADO");
             
             while(result.next()){
                 cestado.addItem(result.getString("EstNom"));
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
        }
           cestado.setVisible(false);
    }
 public void iniciarcombolugargiro(){
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM LUGARGIRO");
             
             while(result.next()){
                 clugar.addItem(result.getString("LugGirNom"));
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
        }
           clugar.setVisible(false);
    }
 public void iniciarcombotipomoneda(){
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM TIPOMONEDA");
             
             while(result.next()){
                 cmoneda.addItem( result.getString("TipMonNom"));
              
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
        }
           cmoneda.setVisible(false);
    }
 public void iniciarcomboaceptante(){
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM ACEPTANTE");
             
             while(result.next()){
                 caceptante.addItem(String.valueOf(result.getInt("AcepCod")));
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
        }
           caceptante.setVisible(false);
    }
 public void iniciarcomboaval(){
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM AVALES");
             
             while(result.next()){
                 caval.addItem(String.valueOf(result.getInt("AvalCod")));
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
        }
           caval.setVisible(false);
    }
 public void iniciarcombobanco(){
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM BANCOS");
             
             while(result.next()){
                 cbanco.addItem(result.getString("BanNom"));
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
        }
           cbanco.setVisible(false);
    }
 public void iniciarrepresentantegirador(){
        try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM REPRESENTANTEGIRADOR");
             
             while(result.next()){
                 crepresentante.addItem(String.valueOf(result.getInt("RepGir")));
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(Level.SEVERE, null, ex);
        }
           crepresentante.setVisible(false);
    }
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTROLETRASCAMBIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTROLETRASCAMBIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton ADICIONAR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton INACTIVAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JButton REACTIVAR;
    private javax.swing.JButton SALIR;
    private javax.swing.JComboBox<String> caceptante;
    private javax.swing.JComboBox<String> caval;
    private javax.swing.JComboBox<String> cbanco;
    private javax.swing.JComboBox<String> cestado;
    private javax.swing.JComboBox<String> clugar;
    private javax.swing.JComboBox<String> cmoneda;
    private javax.swing.JComboBox<String> crepresentante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableregistro;
    private javax.swing.JTextField txtacep;
    private javax.swing.JTextField txtaval;
    private javax.swing.JTextField txtban;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtgiroaño;
    private javax.swing.JTextField txtgirodia;
    private javax.swing.JTextField txtgiromes;
    private javax.swing.JTextField txtlug;
    private javax.swing.JTextField txtmon;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtref1;
    private javax.swing.JTextField txtref2;
    private javax.swing.JTextField txtrep;
    private javax.swing.JTextField txtvenaño;
    private javax.swing.JTextField txtvendia;
    private javax.swing.JTextField txtvenmes;
    private javax.swing.JTextField valbuscar;
    // End of variables declaration//GEN-END:variables
int opcion=0;
int contador=0;
String txlugargiro="";
String txmoneda="";
String txaceptante="";
String txaval="";
String txbanco="";
String txrepresentante="";
String txestado="";
    Conectar co=new Conectar();
Connection connection=co.conexion();



}
