/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package prueba_conexion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nico-
 */
public class REPRESENTANTEGIRADOR extends javax.swing.JFrame {

    /**
     * Creates new form REPRESENTANTEGIRADOR
     */
    public REPRESENTANTEGIRADOR() {
        initComponents();
        mostrar("");
         txtcod.setEditable(false);
        txtdni.setEditable(false);  
        txtap.setEditable(false);
        txtam.setEditable(false);
        txtnom.setEditable(false);
        txtestado.setEditable(false);  
        txtcarg.setEditable(false);
        valbuscar.setEditable(false); 
         cestado.removeAllItems();
            this.iniciarcomboestado();
            cestado.setVisible(false);
            ccargo.removeAllItems();
            this.iniciarcombocargo();
            ccargo.setVisible(false);
            contador++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcarg = new javax.swing.JTextField();
        valbuscar = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();
        MOSTRAR = new javax.swing.JButton();
        cestado = new javax.swing.JComboBox<>();
        ccargo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablerepresentante = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ADICIONAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        INACTIVAR = new javax.swing.JButton();
        REACTIVAR = new javax.swing.JButton();
        ACEPTAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("REPRESENTANTE LEGAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setText("CODIGO:");

        jLabel3.setText("DNI:");

        jLabel4.setText("APELLIDO PATERNO:");

        jLabel5.setText("APELLIDO MATERNO:");

        jLabel6.setText("NOMBRE:");

        jLabel7.setText("ESTADO:");

        jLabel8.setText("CARGO:");

        txtcarg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcargActionPerformed(evt);
            }
        });

        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        MOSTRAR.setText("MOSTRAR");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });

        cestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cestadoActionPerformed(evt);
            }
        });

        ccargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ccargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(65, 65, 65)
                        .addComponent(txtcarg, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ccargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(67, 67, 67)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtap, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel7))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BUSCAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MOSTRAR)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcarg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR)
                    .addComponent(MOSTRAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        tablerepresentante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablerepresentante);

        ADICIONAR.setText("ADICIONAR");
        ADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARActionPerformed(evt);
            }
        });

        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        INACTIVAR.setText("INACTIVAR");
        INACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INACTIVARActionPerformed(evt);
            }
        });

        REACTIVAR.setText("REACTIVAR");
        REACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REACTIVARActionPerformed(evt);
            }
        });

        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ADICIONAR)
                        .addGap(45, 45, 45)
                        .addComponent(MODIFICAR))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(INACTIVAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(REACTIVAR)))
                .addGap(71, 71, 71)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ELIMINAR)
                    .addComponent(ACEPTAR))
                .addGap(71, 71, 71)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SALIR)
                    .addComponent(CANCELAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADICIONAR)
                    .addComponent(MODIFICAR)
                    .addComponent(ELIMINAR)
                    .addComponent(SALIR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INACTIVAR)
                    .addComponent(REACTIVAR)
                    .addComponent(ACEPTAR)
                    .addComponent(CANCELAR))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARActionPerformed
        // TODO add your handling code here:
       if(opcion==0){
        txtdni.setEditable(true);  
        txtap.setEditable(true);
        txtam.setEditable(true);
        txtnom.setEditable(true);
        valbuscar.setEditable(true);
         cestado.setVisible(true);
       ccargo.setVisible(true);
        opcion=1;
       }
    }//GEN-LAST:event_ADICIONARActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
         clean();
        mostrar("");
        opcion=0;
    }//GEN-LAST:event_CANCELARActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
        if(opcion==0){
        int fila=tablerepresentante.getSelectedRow();
         if(fila>=0){
             
             txtcod.setText(tablerepresentante.getValueAt(fila,0).toString());
             txtdni.setText(tablerepresentante.getValueAt(fila,1).toString());
            txtap.setText(tablerepresentante.getValueAt(fila,2).toString());
             txtam.setText(tablerepresentante.getValueAt(fila,3).toString());
             txtnom.setText(tablerepresentante.getValueAt(fila,4).toString());
            txtestado.setText(tablerepresentante.getValueAt(fila,5).toString());
             txtcarg.setText(tablerepresentante.getValueAt(fila,6).toString());
           opcion=3;
        txtcod.setEditable(false);
        txtdni.setEditable(true);  
        txtap.setEditable(true);
        txtam.setEditable(true);
        txtnom.setEditable(true);
        valbuscar.setEditable(true);
         cestado.setVisible(true);
       ccargo.setVisible(true);
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
         }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        // TODO add your handling code here:
          if(opcion==0){
        valbuscar.setEditable(true);
        opcion=2;
          }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
        // TODO add your handling code here:
         mostrar("");
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        // TODO add your handling code here:
         if(opcion==1){
            try {
                PreparedStatement ps=connection.prepareStatement("INSERT INTO REPRESENTANTEGIRADOR (RepGirDNI,RepGirApePat,RepGirApeMat,"
                        + "RepGirNom,ESTADO_EstCod,CARGO_CargCod) VALUES (?,?,?,?,?,?)");
                 ps.setString(1,txtdni.getText());
         ps.setString(2,txtap.getText());
           ps.setString(3,txtam.getText());
         ps.setString(4,txtnom.getText());
           ps.setString(5,txestado);
         ps.setString(6,txcargo);
         ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
            }
             mostrar("");
             }else if(opcion==2){
       mostrar(valbuscar.getText().toString());
        }else if(opcion==3){
            try {
                 if(txestado.equals(""))
                    txestado=txtestado.getText();
                  if(txcargo.equals(""))
                    txcargo=txtcarg.getText();
                PreparedStatement pst=connection.prepareStatement("UPDATE REPRESENTANTEGIRADOR SET RepGirDNI='"
                        +txtdni.getText() +"',RepGirApePat='"+txtap.getText()+"',RepGirApeMat='"+txtam.getText()+
                        "',RepGirNom='"+txtnom.getText()+ "',ESTADO_EstCod='"+txestado+"',CARGO_CargCod='"+txcargo+"' WHERE RepGir='"+
                        txtcod.getText()+"'");
                 pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
            }
             mostrar("");
             }else if(opcion==4){
             String i ="I";
             try {
                 PreparedStatement pst=connection.prepareStatement("UPDATE REPRESENTANTEGIRADOR SET ESTADO_EstCod='"+i+
                         "' WHERE RepGir='"
                         +txtcod.getText()+"'");
                   pst.executeUpdate();
             } catch (SQLException ex) {
                 Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
             }
              mostrar("");
             }else if(opcion==5){
             try {
                 String i ="A";
                 PreparedStatement pst=connection.prepareStatement("UPDATE REPRESENTANTEGIRADOR SET ESTADO_EstCod='"+i+
                         "' WHERE RepGir='"
                         +txtcod.getText()+"'");
                  pst.executeUpdate();
             } catch (SQLException ex) {
                 Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
             }
              mostrar("");
             }else if(opcion==6){
             try {
                  String i ="*";
                 PreparedStatement pst=connection.prepareStatement("UPDATE REPRESENTANTEGIRADOR SET ESTADO_EstCod='"+i+
                         "' WHERE RepGir='"
                         +txtcod.getText()+"'");
                  pst.executeUpdate();
             } catch (SQLException ex) {
                 Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
             }
              mostrar("");
             }
             
         clean();
       opcion=0;
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void INACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INACTIVARActionPerformed
        // TODO add your handling code here:
          if(opcion==0){
        int fila=tablerepresentante.getSelectedRow();
         if(fila>=0){
          txtcod.setText(tablerepresentante.getValueAt(fila,0).toString());
             txtdni.setText(tablerepresentante.getValueAt(fila,1).toString());
            txtap.setText(tablerepresentante.getValueAt(fila,2).toString());
             txtam.setText(tablerepresentante.getValueAt(fila,3).toString());
             txtnom.setText(tablerepresentante.getValueAt(fila,4).toString());
            txtestado.setText(tablerepresentante.getValueAt(fila,5).toString());
             txtcarg.setText(tablerepresentante.getValueAt(fila,6).toString());
           opcion=4;
        }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         } 
         }
    }//GEN-LAST:event_INACTIVARActionPerformed

    private void REACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REACTIVARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){
        int fila=tablerepresentante.getSelectedRow();
         if(fila>=0){
          txtcod.setText(tablerepresentante.getValueAt(fila,0).toString());
             txtdni.setText(tablerepresentante.getValueAt(fila,1).toString());
            txtap.setText(tablerepresentante.getValueAt(fila,2).toString());
             txtam.setText(tablerepresentante.getValueAt(fila,3).toString());
             txtnom.setText(tablerepresentante.getValueAt(fila,4).toString());
            txtestado.setText(tablerepresentante.getValueAt(fila,5).toString());
             txtcarg.setText(tablerepresentante.getValueAt(fila,6).toString());
           opcion=5;
        }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         } 
         }
    }//GEN-LAST:event_REACTIVARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        // TODO add your handling code here:
          if(opcion==0){
        int fila=tablerepresentante.getSelectedRow();
         if(fila>=0){
          txtcod.setText(tablerepresentante.getValueAt(fila,0).toString());
             txtdni.setText(tablerepresentante.getValueAt(fila,1).toString());
            txtap.setText(tablerepresentante.getValueAt(fila,2).toString());
             txtam.setText(tablerepresentante.getValueAt(fila,3).toString());
             txtnom.setText(tablerepresentante.getValueAt(fila,4).toString());
            txtestado.setText(tablerepresentante.getValueAt(fila,5).toString());
             txtcarg.setText(tablerepresentante.getValueAt(fila,6).toString());
           opcion=6;
        }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         } 
         }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void cestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cestadoActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                 ResultSet result=st.executeQuery("SELECT *FROM ESTADO WHERE EstNom='"+cestado.getSelectedItem()+"'");
            result.next();
            txestado=result.getString("EstCod");
            txtestado.setText(txestado);
             } catch (SQLException ex) {
                 Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
             }
         
         }
    }//GEN-LAST:event_cestadoActionPerformed

    private void ccargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccargoActionPerformed
        // TODO add your handling code here:
        if(this.contador>0){ 
             try {
                 Statement st=connection.createStatement();
                 ResultSet result=st.executeQuery("SELECT *FROM CARGO WHERE CargNom='"+ccargo.getSelectedItem()+"'");
            result.next();
            txcargo=String.valueOf(result.getInt("CargCod"));
            txtcarg.setText(txcargo);
             } catch (SQLException ex) {
                 Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
             }
         
         }
        
    }//GEN-LAST:event_ccargoActionPerformed

    private void txtcargActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcargActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcargActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        Conexion_formulario h=new Conexion_formulario();
        h.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
     public void clean(){
    txtcod.setText("");
    txtdni.setText("");
    txtap.setText("");
    txtam.setText("");
    txtnom.setText("");
    txtestado.setText("");
    txtcarg.setText("");
    valbuscar.setText("");
    txtcod.setEditable(false);
        txtdni.setEditable(false);  
        txtap.setEditable(false);
        txtam.setEditable(false);
        txtnom.setEditable(false);
        txtestado.setEditable(false);  
        txtcarg.setEditable(false);
        valbuscar.setEditable(false);  
        cestado.setVisible(false);
         ccargo.setVisible(false);
         txestado="";
         txcargo="";
    }
      public void mostrar(String valor){
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("CODIGO");
     modelo.addColumn("DNI");
      modelo.addColumn("APELLIDO PATERNO");
      modelo.addColumn("APELLIDO MATERNO");
     modelo.addColumn("NOMBRE");
      modelo.addColumn("ESTADO");
       modelo.addColumn("CARGO");
      tablerepresentante.setModel(modelo);
      String datos[]=new String[7]; 
      String texto="SELECT * FROM REPRESENTANTEGIRADOR";
    
    if(valor.equals("")==false)
          texto="SELECT * FROM REPRESENTANTEGIRADOR WHERE RepGir='"+valor+"'";
     
        try {
            Statement st=connection.createStatement();
            ResultSet result=st.executeQuery(texto);
            while(result.next()){
            datos[0]=result.getString(1);
            datos[1]=result.getString(2);
              datos[2]=result.getString(3);
               datos[3]=result.getString(4);
            datos[4]=result.getString(5);
              datos[5]=result.getString(6);
               datos[6]=result.getString(7);
            modelo.addRow(datos);
             }
            tablerepresentante.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
      /**
     * @param args the command line arguments
     */
     public void iniciarcomboestado(){
        
        try {
            Statement st=connection.createStatement();
            ResultSet result=st.executeQuery("SELECT *FROM ESTADO");
             
             while(result.next()){
                 cestado.addItem(result.getString("EstNom"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
        }
             
      
           cestado.setVisible(false);
    }
     public void iniciarcombocargo(){
        
        
        try {
            Statement st=connection.createStatement();
              ResultSet result=st.executeQuery("SELECT *FROM CARGO");
             
             while(result.next()){
                 ccargo.addItem(result.getString("CargNom"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
           ccargo.setVisible(false);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REPRESENTANTEGIRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REPRESENTANTEGIRADOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton ADICIONAR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton INACTIVAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JButton REACTIVAR;
    private javax.swing.JButton SALIR;
    private javax.swing.JComboBox<String> ccargo;
    private javax.swing.JComboBox<String> cestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablerepresentante;
    private javax.swing.JTextField txtam;
    private javax.swing.JTextField txtap;
    private javax.swing.JTextField txtcarg;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField valbuscar;
    // End of variables declaration//GEN-END:variables

    int opcion=0;
    int contador=0;
String txestado="";
String txcargo="";
    Conectar co=new Conectar();
Connection connection=co.conexion();

}
