/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba_conexion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nico-
 */
public class SUCURSALES extends javax.swing.JFrame {

    /**
     * Creates new form SUCURSALES
     */
    public SUCURSALES() {
        initComponents();
         mostrar("");
         txtcod.setEditable(false);
        txtofi.setEditable(false);  
        txtdir.setEditable(false);
        txtbanco.setEditable(false);
        txtlug.setEditable(false);
        txtestado.setEditable(false);  
        valbuscar.setEditable(false);  
         cestado.removeAllItems();
            this.iniciarcomboestado();
            cestado.setVisible(false);
            clugargiro.removeAllItems();
            this.iniciarcombolugargiro();
            clugargiro.setVisible(false);
            cbanco.removeAllItems();
            this.iniciarcombobanco();
            cbanco.setVisible(false);
            contador++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtofi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtbanco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtlug = new javax.swing.JTextField();
        labelestado = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        valbuscar = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();
        MOSTRAR = new javax.swing.JButton();
        clugargiro = new javax.swing.JComboBox<>();
        cbanco = new javax.swing.JComboBox<>();
        cestado = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesucursales = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ADICIONAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        INACTIVAR = new javax.swing.JButton();
        REACTIVAR = new javax.swing.JButton();
        ACEPTAR = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("SUCUSALES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setText("CODIGO:");

        jLabel3.setText("OFICINA:");

        txtofi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtofiActionPerformed(evt);
            }
        });

        jLabel4.setText("DIRRECCION:");

        jLabel5.setText("BANCO:");

        jLabel6.setText("LUGAR DE GIRO:");

        labelestado.setText("ESTADO:");

        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        MOSTRAR.setText("MOSTRAR");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });

        clugargiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clugargiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clugargiroActionPerformed(evt);
            }
        });

        cbanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbancoActionPerformed(evt);
            }
        });

        cestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cestadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BUSCAR)
                                .addGap(18, 18, 18)
                                .addComponent(MOSTRAR)
                                .addGap(56, 56, 56)
                                .addComponent(labelestado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtofi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(clugargiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtbanco, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(cbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtlug, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtofi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtlug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clugargiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR)
                    .addComponent(MOSTRAR)
                    .addComponent(labelestado)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tablesucursales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablesucursales);

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));

        ADICIONAR.setText("ADICIONAR");
        ADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARActionPerformed(evt);
            }
        });

        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        INACTIVAR.setText("INACTIVAR");
        INACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INACTIVARActionPerformed(evt);
            }
        });

        REACTIVAR.setText("REACTIVAR");
        REACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REACTIVARActionPerformed(evt);
            }
        });

        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });

        CANCELAR.setText("CANCELAR");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INACTIVAR)
                    .addComponent(ADICIONAR))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(MODIFICAR)
                        .addGap(52, 52, 52)
                        .addComponent(ELIMINAR))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(REACTIVAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ACEPTAR)))
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SALIR)
                    .addComponent(CANCELAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADICIONAR)
                    .addComponent(MODIFICAR)
                    .addComponent(ELIMINAR)
                    .addComponent(SALIR))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INACTIVAR)
                    .addComponent(REACTIVAR)
                    .addComponent(ACEPTAR)
                    .addComponent(CANCELAR))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtofiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtofiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtofiActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
          clean();
        mostrar("");
        opcion=0;
    }//GEN-LAST:event_CANCELARActionPerformed

    private void ADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){
        txtcod.setEditable(false);
        txtofi.setEditable(true);  
        txtdir.setEditable(true);
        valbuscar.setEditable(true);
        cestado.setVisible(true);
        cbanco.setVisible(true);
        clugargiro.setVisible(true);
        opcion=1;
    }//GEN-LAST:event_ADICIONARActionPerformed
    }
    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        // TODO add your handling code here:
         if(opcion==1){
             try {
                 PreparedStatement ps=connection.prepareStatement("INSERT INTO SUCURSALES (SucNomOfi,SucDir,BANCOS_BanCod,"
                         + "LUGARGIRO_LugGirCod,ESTADO_EstCod) VALUES (?,?,?,?,?)");
                  ps.setString(1,txtofi.getText());
         ps.setString(2,txtdir.getText());
           ps.setString(3,txbanco);
         ps.setString(4,txlugargiro);
           ps.setString(5,txestado);
         ps.executeUpdate();
             } catch (SQLException ex) {
                 Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
             }
             mostrar("");
            }else if(opcion==2){
       mostrar(valbuscar.getText().toString());
        }else if(opcion==3){
             if(txestado.equals(""))
                    txestado=txtestado.getText();
                  if(txlugargiro.equals(""))
                    txlugargiro=txtlug.getText();
                   if(txbanco.equals(""))
                    txbanco=txtbanco.getText();
                  
             try {
                 PreparedStatement pst=connection.prepareStatement("UPDATE SUCURSALES SET SucNomOfi='"
                         +txtofi.getText() +"',SucDir='"+txtdir.getText()+"',BANCOS_BanCod='"+txbanco+
                         "',LUGARGIRO_LugGirCod='"+txlugargiro+ "',ESTADO_EstCod='"+txestado+"' WHERE SucCod='"+
                         txtcod.getText()+"'");
                  pst.executeUpdate();
             } catch (SQLException ex) {
                 Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
             }
         mostrar("");
            }else if(opcion==4){
             String i ="I";
             try {
                 PreparedStatement pst=connection.prepareStatement("UPDATE SUCURSALES SET ESTADO_EstCod='"+i+
                         "' WHERE SucCod='"
                         +txtcod.getText()+"'");
                  pst.executeUpdate();
             } catch (SQLException ex) {
                 Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
             }
                 mostrar("");
             }else if(opcion==5){
             String i ="A";
             try {
                 PreparedStatement pst=connection.prepareStatement("UPDATE SUCURSALES SET ESTADO_EstCod='"+i+
                         "' WHERE SucCod='"
                         +txtcod.getText()+"'");
                  pst.executeUpdate();
             } catch (SQLException ex) {
                 Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
             }
              mostrar("");
             }else if(opcion==6){
             try {
                 String i ="*";
               PreparedStatement pst=connection.prepareStatement("UPDATE SUCURSALES SET ESTADO_EstCod='"+i+
                         "' WHERE SucCod='"
                         +txtcod.getText()+"'");
                  pst.executeUpdate();  
             } catch (SQLException ex) {
                 Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
             }
             mostrar("");
             }
           clean();
       opcion=0;
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){
        valbuscar.setEditable(true);
        opcion=2;
         }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
        // TODO add your handling code here:
         mostrar("");
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
        if(opcion==0){
        int fila=tablesucursales.getSelectedRow();
         if(fila>=0){
             txtcod.setText(tablesucursales.getValueAt(fila,0).toString());
            txtofi.setText(tablesucursales.getValueAt(fila,1).toString());
             txtdir.setText(tablesucursales.getValueAt(fila,2).toString());
            txtbanco.setText(tablesucursales.getValueAt(fila,3).toString());
             txtlug.setText(tablesucursales.getValueAt(fila,4).toString());
             txtestado.setText(tablesucursales.getValueAt(fila,5).toString());
            opcion=3;
        txtcod.setEditable(false);
        txtofi.setEditable(true);  
        txtdir.setEditable(true);
        valbuscar.setEditable(true);
         cestado.setVisible(true);
        cbanco.setVisible(true);
        clugargiro.setVisible(true);
         }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         }
         }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void INACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INACTIVARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){
        int fila=tablesucursales.getSelectedRow();
         if(fila>=0){
          txtcod.setText(tablesucursales.getValueAt(fila,0).toString());
             txtofi.setText(tablesucursales.getValueAt(fila,1).toString());
            txtdir.setText(tablesucursales.getValueAt(fila,2).toString());
             txtbanco.setText(tablesucursales.getValueAt(fila,3).toString());
             txtlug.setText(tablesucursales.getValueAt(fila,4).toString());
            txtestado.setText(tablesucursales.getValueAt(fila,5).toString());
            opcion=4;
        }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         } 
         }
    }//GEN-LAST:event_INACTIVARActionPerformed

    private void REACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REACTIVARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){
        int fila=tablesucursales.getSelectedRow();
         if(fila>=0){
          txtcod.setText(tablesucursales.getValueAt(fila,0).toString());
             txtofi.setText(tablesucursales.getValueAt(fila,1).toString());
            txtdir.setText(tablesucursales.getValueAt(fila,2).toString());
             txtbanco.setText(tablesucursales.getValueAt(fila,3).toString());
             txtlug.setText(tablesucursales.getValueAt(fila,4).toString());
            txtestado.setText(tablesucursales.getValueAt(fila,5).toString());
            opcion=5;
        }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         } 
         }
    }//GEN-LAST:event_REACTIVARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        // TODO add your handling code here:
         if(opcion==0){
        int fila=tablesucursales.getSelectedRow();
         if(fila>=0){
          txtcod.setText(tablesucursales.getValueAt(fila,0).toString());
             txtofi.setText(tablesucursales.getValueAt(fila,1).toString());
            txtdir.setText(tablesucursales.getValueAt(fila,2).toString());
             txtbanco.setText(tablesucursales.getValueAt(fila,3).toString());
             txtlug.setText(tablesucursales.getValueAt(fila,4).toString());
            txtestado.setText(tablesucursales.getValueAt(fila,5).toString());
            opcion=6;
        }else{
         JOptionPane.showMessageDialog(null,"fila no seleccionada");
         } 
         }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void cbancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbancoActionPerformed
        // TODO add your handling code here:
        if(this.contador>0){ 
             
            try {
                Statement st=connection.createStatement();
                 ResultSet result=st.executeQuery("SELECT *FROM BANCOS WHERE BanNom='"+cbanco.getSelectedItem()+"'");
            result.next();
            txbanco=String.valueOf(result.getInt("BanCod"));
            txtbanco.setText(txbanco);
            } catch (SQLException ex) {
                Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
    }//GEN-LAST:event_cbancoActionPerformed

    private void clugargiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clugargiroActionPerformed
        // TODO add your handling code here:
           if(this.contador>0){ 
             
            try {
                Statement st=connection.createStatement();
                 ResultSet result=st.executeQuery("SELECT *FROM LUGARGIRO WHERE LugGirNom='"+clugargiro.getSelectedItem()+"'");
            result.next();
            txlugargiro=result.getString("LugGirCod");
            txtlug.setText(txlugargiro);
            } catch (SQLException ex) {
                Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
    }//GEN-LAST:event_clugargiroActionPerformed

    private void cestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cestadoActionPerformed
        // TODO add your handling code here:
         if(this.contador>0){ 
             try {
                Statement st=connection.createStatement();
                 ResultSet result=st.executeQuery("SELECT *FROM ESTADO WHERE EstNom='"+cestado.getSelectedItem()+"'");
            result.next();
            txestado=result.getString("EstCod");
            txtestado.setText(txestado);
            } catch (SQLException ex) {
                Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
    }//GEN-LAST:event_cestadoActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        Conexion_formulario h=new Conexion_formulario();
        h.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public void clean(){
    txtcod.setText("");
    txtofi.setText("");
    txtdir.setText("");
    txtbanco.setText("");
    txtlug.setText("");
    txtestado.setText("");
    valbuscar.setText("");
    txtcod.setEditable(false);
        txtofi.setEditable(false);  
        txtdir.setEditable(false);
        txtbanco.setEditable(false);
        txtlug.setEditable(false);
        txtestado.setEditable(false);  
        valbuscar.setEditable(false);  
     cestado.setVisible(false);
    txestado="";
     cbanco.setVisible(false);
    txbanco="";
     clugargiro.setVisible(false);
    txlugargiro="";
    }
     public void mostrar(String valor){
    DefaultTableModel modelo=new DefaultTableModel();
    modelo.addColumn("CODIGO");
     modelo.addColumn("OFICINA");
      modelo.addColumn("DIRRECCION");
      modelo.addColumn("BANCO");
     modelo.addColumn("LUGAR DE GIRO");
      modelo.addColumn("ESTADO");
       tablesucursales.setModel(modelo);
      String datos[]=new String[6]; 
      String texto="SELECT * FROM SUCURSALES";
    if(valor.equals("")==false)
          texto="SELECT * FROM SUCURSALES WHERE SucCod='"+valor+"'";
        try {
            Statement st=connection.createStatement();
           ResultSet result=st.executeQuery(texto);
            while(result.next()){
            datos[0]=result.getString(1);
            datos[1]=result.getString(2);
              datos[2]=result.getString(3);
               datos[3]=result.getString(4);
            datos[4]=result.getString(5);
              datos[5]=result.getString(6);
               modelo.addRow(datos);
             }
            tablesucursales.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
     
      public void iniciarcombolugargiro(){
         try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM LUGARGIRO");
             
             while(result.next()){
                 clugargiro.addItem(result.getString("LugGirNom"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
     public void iniciarcombobanco(){
       try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM BANCOS");
             
             while(result.next()){
                 cbanco.addItem(result.getString("BanNom"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
     public void iniciarcomboestado(){
       try {
            Statement st=connection.createStatement();
             ResultSet result=st.executeQuery("SELECT *FROM ESTADO");
             
             while(result.next()){
                 cestado.addItem(result.getString("EstNom"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SUCURSALES.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SUCURSALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SUCURSALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SUCURSALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SUCURSALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SUCURSALES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton ADICIONAR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton INACTIVAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JButton REACTIVAR;
    private javax.swing.JButton SALIR;
    private javax.swing.JComboBox<String> cbanco;
    private javax.swing.JComboBox<String> cestado;
    private javax.swing.JComboBox<String> clugargiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelestado;
    private javax.swing.JTable tablesucursales;
    private javax.swing.JTextField txtbanco;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtlug;
    private javax.swing.JTextField txtofi;
    private javax.swing.JTextField valbuscar;
    // End of variables declaration//GEN-END:variables
int opcion=0;
 int contador=0;
String txbanco="";
String txlugargiro="";
String txestado="";
    Conectar co=new Conectar();
Connection connection=co.conexion();

}
